import './nodejs/authors-create.js'
import './nodejs/authors-list.js'

import './nodejs/blobs-add.js'
import './nodejs/blobs-list-blobs.js'
import './nodejs/blobs-list-collections.js'
import './nodejs/blobs-list-incomplete-blobs.js'

import './nodejs/docs-delete.js'
import './nodejs/docs-drop.js'
import './nodejs/docs-export.js'
import './nodejs/docs-get.js'
import './nodejs/docs-import.js'
import './nodejs/docs-join.js'
import './nodejs/docs-keys.js'
import './nodejs/docs-list.js'
import './nodejs/docs-set.js'
import './nodejs/docs-share.js'
import './nodejs/docs-watch.js'