export const protocols = [
  {
    "featured": 1,
    "icon": "iconOpen",
    "title": "Blobs",
    "tagline": "Resumable, verifiable data transfer",
    "slug": "iroh-blobs",
    "repository": "https://github.com/n0-computer/iroh-blobs",
    "documentation": "https://docs.rs/iroh-blobs/latest/iroh_blobs/",
    "version": "v0.35.0" // TODO - pull version from github
  },
  {
    "featured": 2,
    "icon": "iconPlatforms",
    "title": "Gossip",
    "tagline": "Broadcast messages to groups of nodes by topic.",
    "slug": "iroh-gossip",
    "repository": "https://github.com/n0-computer/iroh-gossip",
    "documentation": "https://docs.rs/iroh-gossip/latest/iroh_gossip/",
    "version": "v0.35.0" // TODO - pull version from github
  },
  {
    "featured": 3,
    "icon": "iconFaster",
    "title": "Documents",
    "tagline": "Realtime, multiwriter, key-value sync",
    "slug": "iroh-docs",
    "documentation": "https://docs.rs/iroh-docs/latest/iroh_docs/",
    "repository": "https://github.com/n0-computer/iroh-docs",
    "version": "v0.35.0" // TODO - pull version from github
  },
  {
    "icon": "",
    "title": "iroh-roq",
    "tagline": "RTP over QUIC implemented as iroh protocol",
    "slug": "iroh-roq",
    "documentation": "https://docs.rs/iroh-roq/latest/iroh_roq/",
    "repository": "https://github.com/n0-computer/iroh-roq",
    "version": "v0.1.0"
  },
  {
    "icon": "",
    "title": "Godot iroh",
    "tagline": "A peer-to-peer multiplayer extension for Godot based on Iroh.",
    "slug": "godot-iroh",
    "documentation": "https://godotengine.org/asset-library/asset/3948",
    "repository": "https://github.com/tipragot/godot-iroh",
    "version": "v0.1.5"
  },
  {
    "icon": "",
    "title": " Iroh Content Discovery",
    "tagline": "A protocol to communicate with a content tracker for iroh-blobs.",
    "slug": "iroh-content-discovery",
    "documentation": "https://docs.rs/iroh-content-discovery/latest/iroh_content_discovery/",
    "repository": "https://github.com/tipragot/godot-iroh",
    "version": "v0.1.0",
    experimental: true,
  },
  {
    "icon": "",
    "title": "Iroh ping",
    "tagline": "A minimal protocol to ping iroh nodes.",
    "slug": "iroh-ping",
    "documentation": "https://docs.rs/iroh-ping/latest/iroh_ping/",
    "repository": "https://github.com/n0-computer/iroh-ping",
    "version": "v0.2.0"
  },
  {
    "icon": "",
    "title": "Iroh protocol for Rateless IBLTs",
    "tagline": "Set reconciliation with RIBLTs, as an iroh protocol",
    "slug": "iroh-riblt",
    "documentation": "https://github.com/b5/iroh-riblt",
    "repository": "https://github.com/b5/iroh-riblt",
    "version": "v0.1.0 (unpublished)",
    experimental: true,
  },

  {
    "icon": "",
    "title": "Iroh protocol for range-based set reconciliation",
    "tagline": "Range-based set reconciliation as an iroh protocol",
    "slug": "iroh-ranger",
    "documentation": "https://github.com/b5/iroh-ranger",
    "repository": "https://github.com/b5/iroh-ranger",
    "version": "v0.1.0 (unpublished)",
    experimental: true,
  },
  {
    "icon": "",
    "title": "Using iroh as a dumb pipe",
    "tagline": "Just a dumb pipe",
    "slug": "dumbpipe",
    "documentation": "https://docs.rs/dumbpipe/latest/dumbpipe/",
    "repository": "https://github.com/n0-computer/dumbpipe",
    "version": "v0.28.0"
  },
  {
    "icon": "",
    "title": "Frosty threshold signatures",
    "tagline": "A protocol for threshold signatures using the frost scheme.",
    "slug": "frosty",
    "documentation": "https://github.com/n0-computer/iroh-examples/tree/main/frosty",
    "repository": "https://github.com/n0-computer/iroh-examples/tree/main/frosty",
    "version": "v0.1.0 (unpublished)",
    experimental: true,
  },
  {
    "icon": "",
    "title": "Frosty threshold signatures",
    "tagline": "A protocol for threshold signatures using the frost scheme.",
    "slug": "Iroh automerge",
    "documentation": "https://github.com/n0-computer/iroh-examples/tree/main/iroh-automerge",
    "repository": "https://github.com/n0-computer/iroh-examples/tree/main/iroh-automerge",
    "version": "v0.1.0 (unpublished)",
    experimental: true,
  },
  {
    "icon": "",
    "title": "Beelay/Keyhive Iroh Protocol",
    "tagline": "Custom Iroh Protocol for integrating Beelay/Keyhive",
    "slug": "iroh-beelay",
    "documentation": "https://github.com/symplasma/custom_beelay_iroh_protocol",
    "repository": "https://github.com/symplasma/custom_beelay_iroh_protocol",
    "version": "v0.1.0 (unpublished)",
    experimental: true,
  }
]
